export const LOG_USER_IN = "LOG_USER_IN";
export const LOG_USER_OUT = "LOG_USER_OUT";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const SHOW_GLOBAL_ISSUES = "SHOW_GLOBAL_ISSUES";
export const SHOW_USER_ISSUES = "SHOW_USER_ISSUES";
